[package]
name = "rotfor"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rotfor"
path = "src/main.rs"

[lib]
name = "rotfor"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
rand = "0.9.0"
